name: Jobs and steps
on: push
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"
      - name: Set color
        id: color-generator
        run: echo "SELECT_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "${{ steps.color-generator.t.SELECT_COLOR }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: $ {{ github.job }}"
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"
  manual-approval:
    name: Manual Approval
    needs: [job_2, job_3]
    runs-on: ubuntu-latest
    steps:
       - uses: trstringer/manual-approval@v1
         with:
            secret: ${{ github.token }}
            approvers: fofanaabou
            minimum-approvals: 1
            issue-title: "Deploying v1.3.5 to prod from staging"
            issue-body: "Please approve or deny the deployment of version v1.3.5."
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''
  job_4:
    runs-on: ubuntu-latest
    needs: manual-approval
    environment:
      name: production
    steps:
      - run: "echo Job: ${{ github.job }}"
      - name: command
        run: echo "::workflow-command parameter1={data},parameter2={data}::{command value}"