name: Jobs and steps
on: push
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"
      - name: Set color
        id: color-generator
        run: echo "SELECT_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "${{ steps.color-generator.t.SELECT_COLOR }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: $ {{ github.job }}"
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"
  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    environment:
      name: production
    steps:
      - run: "echo Job: ${{ github.job }}"
      - name: command
        run: echo "::workflow-command parameter1={data},parameter2={data}::{command value}"