name: Issue triage
on:
  issues:
    types:
      - opened
      - edited
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          if (${{ contains($BODY, 'bug') }}) {
            echo '::add-labels: bug';
          } else if (${{ contains(BODY, 'feature')}} ) {
            echo '::add-labels: feature';
          } else {
            echo 'Labeling issue as needs-triage';
            echo '::add-labels: needs-triage';
          }